version: "3.9"

services:
  api1:
    build:
      context: ..               
      dockerfile: build/Dockerfile
    container_name: go-api-1
    expose:
      - "8080:8080"
    environment:
      - API_NAME=API-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
  
  api2:
    build:
      context: ..               
      dockerfile: build/Dockerfile
    container_name: go-api-2
    expose:
      - "8081:8080"
    environment:
      - API_NAME=API-2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healtcheck"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:1.25
    container_name: nginx-proxy
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:3000"
    depends_on:
      - api1
      - api2
